### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by nukeop** [AlphaDelta/PNG-Mask#2]
Hello, is this project still alive?

I have developed a similar program in python and I'm interested about the methods this program uses.

How do the hiding algorithms work? Has it been tested if they affect the image's histogram in a significant way?

I'm asking these questions to gain a better understanding of the project and its future, as I'm interested in contributing (and probably also adapting this project's methods to use in my own program).

Thanks

**Comment by AlphaDelta** [comment]
It's not really alive, mostly because I see no purpose in adding anything else considering there's both graphical and non-graphical steganography methods as well as password protection.

I can't explain exactly how the program works because I haven't actually worked in the project in a while but I can explain how the methods store data in an image.

The XOR methods work by adding either a fake critical chunk (IDAT), an ancillary chunk (tEXt), an arbitrary chunk (which I don't use because it would be obvious steganography), or adding it past the end-of-image chunk (IEND, which _is_ and obvious steganography but I thought I would include it anyway). To protect the data I used the data from the PNG's IDAT chunk to seed the ISAAC CPRNG and used that to XOR the steganography data (hence why I called them XOR methods).

The color crash method words by taking the LSB (Least Significant Bytes) in the image bitmap data and replacing them with the bits of the steganography data.

Each method also adds an arbitrary amount of trash before the data (0-255 bytes of trash) as a small form of mitigation for detection.

**Comment by AlphaDelta** [comment]
It's not really alive, mostly because I see no purpose in adding anything else considering there's both graphical and non-graphical steganography methods as well as password protection.

I can't explain exactly how the program work because I haven't actually worked in the project in a while but I can explain how the methods store data in an image.

The XOR methods work by adding either a fake critical chunk (IDAT), an ancillary chunk (tEXt), an arbitrary chunk (which I don't use because it would be obvious steganography), or adding it past the end-of-image chunk (IEND, which _is_ and obvious steganography but I thought I would include it anyway). To protect the data I used the data from the PNG's IDAT chunk to seed the ISAAC CPRNG and used that to XOR the steganography data (hence why I called them XOR methods).

The color crash method words by taking the LSB (Least Significant Bytes) in the image bitmap data and replacing them with the bits of the steganography data.

Each method also adds an arbitrary amount of trash before the data (0-255 bytes of trash) as a small form of mitigation for detection.
